name: Astro check

on:
  pull_request:
    types: 
      - opened
      - reopened
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  check:
    name: astro check
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Status
        run: git status

      - name: astro check
        run: pnpm run test:check-examples
